{
 "title": "Threads Gate",
 "description": "based on Spring Boot2 Statistic by micrometer-prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\"}",
     "legendFormat": "Load Average [1m]"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Queue lengths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"queue_.*_queueLength\", instance=\"$instance\"}, \"className\", \"$1\", \"__name__\", \"queue_(.*)_queueLength\")",
     "legendFormat": "{{className}}"
    }
   ]
  },
  {
   "title": "Queue Items Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"queue_.*_itemsPerMinute\", instance=\"$instance\"}, \"className\", \"$1\", \"__name__\", \"queue_(.*)_itemsPerMinute\")",
     "legendFormat": "{{className}}"
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"cache_.*\", instance=\"$instance\"}, \"cacheName\", \"$1\", \"__name__\", \"cache_(.*)\")",
       "legendFormat": "{{cacheName}}"
      }
     ]
    }
   ]
  },
  { "title": "Message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "In Message Periods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "in_message_period_5{instance=\"$instance\"}",
     "legendFormat": "5"
    },
    {
     "expr": "in_message_period_15{instance=\"$instance\"}",
     "legendFormat": "15"
    },
    {
     "expr": "in_message_period_60{instance=\"$instance\"}",
     "legendFormat": "60"
    },
    {
     "expr": "in_message_period_300{instance=\"$instance\"}",
     "legendFormat": "300"
    },
    {
     "expr": "out_message_period_900{instance=\"$instance\"}",
     "legendFormat": "900"
    },
    {
     "expr": "in_message_period_3600{instance=\"$instance\"}",
     "legendFormat": "3600"
    },
    {
     "expr": "in_message_period_43200{instance=\"$instance\"}",
     "legendFormat": "43200"
    }
   ]
  },
  {
   "title": "In Message Periods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "in_message_period_5{instance=\"$instance\"}",
     "legendFormat": "5"
    },
    {
     "expr": "in_message_period_15{instance=\"$instance\"}",
     "legendFormat": "15"
    },
    {
     "expr": "in_message_period_60{instance=\"$instance\"}",
     "legendFormat": "60"
    },
    {
     "expr": "in_message_period_300{instance=\"$instance\"}",
     "legendFormat": "300"
    },
    {
     "expr": "in_message_period_900{instance=\"$instance\"}",
     "legendFormat": "900"
    },
    {
     "expr": "in_message_period_3600{instance=\"$instance\"}",
     "legendFormat": "3600"
    },
    {
     "expr": "in_message_period_43200{instance=\"$instance\"}",
     "legendFormat": "43200"
    }
   ]
  },
  {
   "title": "Out Message Periods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "out_message_period_5{instance=\"$instance\"}",
     "legendFormat": "5"
    },
    {
     "expr": "out_message_period_15{instance=\"$instance\"}",
     "legendFormat": "15"
    },
    {
     "expr": "out_message_period_60{instance=\"$instance\"}",
     "legendFormat": "60"
    },
    {
     "expr": "out_message_period_300{instance=\"$instance\"}",
     "legendFormat": "300"
    },
    {
     "expr": "out_message_period_900{instance=\"$instance\"}",
     "legendFormat": "900"
    },
    {
     "expr": "out_message_period_3600{instance=\"$instance\"}",
     "legendFormat": "3600"
    },
    {
     "expr": "out_message_period_43200{instance=\"$instance\"}",
     "legendFormat": "43200"
    }
   ]
  },
  {
   "title": "Out Message Periods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "targets": [
    {
     "expr": "out_message_period_5{instance=\"$instance\"}",
     "legendFormat": "5"
    },
    {
     "expr": "out_message_period_15{instance=\"$instance\"}",
     "legendFormat": "15"
    },
    {
     "expr": "out_message_period_60{instance=\"$instance\"}",
     "legendFormat": "60"
    },
    {
     "expr": "out_message_period_300{instance=\"$instance\"}",
     "legendFormat": "300"
    },
    {
     "expr": "out_message_period_900{instance=\"$instance\"}",
     "legendFormat": "900"
    },
    {
     "expr": "out_message_period_3600{instance=\"$instance\"}",
     "legendFormat": "3600"
    },
    {
     "expr": "out_message_period_43200{instance=\"$instance\"}",
     "legendFormat": "43200"
    }
   ]
  },
  {
   "title": "In messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(in_message_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "In messages"
    }
   ]
  },
  {
   "title": "Out messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(out_message_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "Out messages"
    }
   ]
  },
  {
   "title": "In message statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(in_message_status_count_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Out message statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(out_message_status_count_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Out message get new status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(in_message_get_new_statuses_count_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Out message get status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(in_message_get_statuses_count_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Websocket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "websocket_sessions_active{instance=\"$instance\"}",
       "legendFormat": "Sessions"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "websocket_connections_active{instance=\"$instance\"}",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "Rejected Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(websocket_sessions_rejected_total{instance=\"$instance\"}[1m])",
       "legendFormat": "Rejected Sessions"
      }
     ]
    },
    {
     "title": "Rejected Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(websocket_connections_rejected_total{instance=\"$instance\"}[1m])",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "Register Device (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"registerDevice\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"registerDevice\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"registerDevice\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"registerDevice\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    },
    {
     "title": "Send Message (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"sendMessage\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"sendMessage\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"sendMessage\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"sendMessage\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    },
    {
     "title": "Register Device Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(method_timed_seconds_sum{instance=\"$instance\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"registerDevice\", exception=\"none\"}[5m]) / irate(method_timed_seconds_count{instance=\"$instance\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"registerDevice\", exception=\"none\"}[5m])",
       "legendFormat": "Time"
      }
     ]
    },
    {
     "title": "Send Message Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(method_timed_seconds_sum{instance=\"$instance\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"sendMessage\", exception=\"none\"}[5m]) / irate(method_timed_seconds_count{instance=\"$instance\", class=\"com.mfms.websocket.server.domain.services.WebSocketService\", method=\"sendMessage\", exception=\"none\"}[5m])",
       "legendFormat": "Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Rest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send Message (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessage\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessage\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessage\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessage\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    },
    {
     "title": "Send Batch Messages (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessages\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessages\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessages\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"sendOutMessages\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    },
    {
     "title": "Get Out Message Status (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatus\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatus\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatus\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatus\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    },
    {
     "title": "Get Out Message Statuses (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatuses\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatuses\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatuses\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getOutMessageStatuses\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    },
    {
     "title": "Get Status (Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getStatus\", exception=\"none\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.95\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getStatus\", exception=\"none\"}",
       "legendFormat": "0.95"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.999\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getStatus\", exception=\"none\"}",
       "legendFormat": "0.99"
      },
      {
       "expr": "method_timed_seconds{instance=\"$instance\", quantile = \"0.5\", class=\"com.mfms.rest.server.domain.web.controllers.RestOutMessageController\", method=\"getStatus\", exception!~\"none\"}",
       "legendFormat": "0.95 {{exception}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$instance\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
       "legendFormat": "Live"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", uri!~\".*actuator.*\", method!=\"OPTIONS\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", exception=\"None\", uri!~\".*actuator.*\", method!=\"OPTIONS\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", exception=\"None\", uri!~\".*actuator.*\", method!=\"OPTIONS\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jetty_threads_current{instance=\"$instance\"}",
       "legendFormat": "Current thread"
      },
      {
       "expr": "jetty_threads_busy{instance=\"$instance\"}",
       "legendFormat": "Current thread busy"
      },
      {
       "expr": "jetty_threads_config_max{instance=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jetty_threads_jobs{instance=\"$instance\"}",
       "legendFormat": "Jobs"
      }
     ]
    }
   ]
  },
  {
   "title": "Logger Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logger Events",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", level=\"info\"}[5m])",
       "legendFormat": "Info"
      },
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", level=\"warn\"}[5m])",
       "legendFormat": "Warning"
      },
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", level=\"error\"}[5m])",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  }
 ]
}