server:
  port: 8083

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

images:
  available-sizes: 200-200.jpg

minio:
  url: http://localhost:9005
  bucket: tonkoslovie-media
  access-key: tonkoslovie
  secret-key: 12345678

management:
  server:
    port: 8183
  endpoints:
    web:
      exposure:
        include: health
  metrics:
    export:
      influx:
        enabled: ${INFLUXDB_ENABLED:false}
        db: tonkoslovie
        org: tonkoslovie
        bucket: tonkoslovie
        uri: ${INFLUXDB_URI}
        user-name: ${INFLUXDB_USER}
        password: ${INFLUXDB_PASSWORD}
        token: ${INFLUXDB_ADMIN_TOKEN}
        step: 10s
        api-version: v2
    tags:
      service.name: ${SERVICE_NAME:media.test}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%4.-4thread] %clr(%level) %clr([%c{1}]){cyan} %m%n%wEx"
  level:
    root: info