server:
  port: 8082

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

images:
  available-sizes: 200-200.jpg

minio:
  bucket: tonkoslovie-media
  url: ${MINIO_URL:http://localhost:9005}
  access-key: ${MINIO_ACCESS_KEY:tonkoslovie}
  secret-key: ${MINIO_SECRET_KEY:12345678}

management:
  server:
    port: 8182
  endpoints:
    web:
      exposure:
        include: health
  influx:
    metrics:
      export:
        enabled: ${INFLUXDB_ENABLED:false}
        db: tonkoslovie
        org: tonkoslovie
        bucket: tonkoslovie
        uri: ${INFLUXDB_URI}
        user-name: ${INFLUXDB_USER}
        password: ${INFLUXDB_PASSWORD}
        token: ${INFLUXDB_ADMIN_TOKEN}
        step: 10s
        api-version: v2
  metrics:
    tags:
      service.name: ${SERVICE_NAME:media.dev}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%4.-4thread] %clr(%level) %clr([%c{1}]){cyan} %m%n%wEx"
  level:
    root: info