version: '2.3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: tonkoslovie_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tonkoslovie
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 3s
        retries: 5

  redis:
    image: redis:5-alpine
    container_name: tonkoslovie_redis
    ports:
      - 6379:6379
    command: redis-server --requirepass 1234
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 5