version: '2.3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: tonkoslovie_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tonkoslovie
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 3s
        retries: 5