version: '2.3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: tonkoslovie_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tonkoslovie
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 3s
        retries: 5

  redis:
    image: redis:5-alpine
    container_name: tonkoslovie_redis
    ports:
      - 6379:6379
    command: redis-server --requirepass 1234
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  influxdb:
    image: influxdb:1.7-alpine
    container_name: tonkoslovie_influx
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=tonkoslovie
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-1234}
      - INFLUXDB_USER=${INFLUXDB_USER:-user}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-1234}
      - INFLUXDB_HTTP_LOG_ENABLED=false
    healthcheck:
      test: ["CMD-SHELL", "ln -sf /bin/busybox /bin/wget && /bin/wget -q -Y off http://localhost:8086/metrics -O /dev/null > /dev/null 2>&1"]
      interval: 10s
      timeout: 3s
      retries: 5