ALTER TABLE lesson REPLICA IDENTITY FULL;
ALTER TABLE text REPLICA IDENTITY FULL;
ALTER TABLE exercise REPLICA IDENTITY FULL;
ALTER TABLE theme REPLICA IDENTITY FULL;
ALTER TABLE word REPLICA IDENTITY FULL;

ALTER TABLE lesson_texts REPLICA IDENTITY FULL;
ALTER TABLE theme_exercises REPLICA IDENTITY FULL;