apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    isDefault: true
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: $INFLUXDB_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: tonkoslovie
      defaultBucket: tonkoslovie
      tlsSkipVerify: true