app:
  host: https://tonkoslovie.ru
  siteHost: https://tonkoslovie.ru

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ru.romanov.tonkoslovie.utils.JsonPostgresDialect

hikari:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost/tonkoslovie
    maximumPoolSize: 25

redis:
  port: 6378

security:
  oauth2:
    successRedirectUrl: https://tonkoslovie.ru/

metrics:
  influxdb:
    active: true