spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: ${database.username}
    password: ${database.password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: ru.romanov.tonkoslovie.utils.JsonPostgresDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
  http:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

redis:
  host: 127.0.0.1
  port: 6379

metrics:
  influxdb:
    active: false
    host: 127.0.0.1
    port: 8086
    database: tonkoslovie
    auth: ${influx.auth}
  console: false

mail:
  host: http://localhost:8080

media:
  imageDirectory: /app/tonkoslovie/images
  soundDirectory: /app/tonkoslovie/sounds

security:
  oauth2:
    successRedirectUrl: http://localhost:3000/

google:
  client:
    clientId: ${oauth.google.clientId}
    clientSecret: ${oauth.google.secret}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - openid
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

facebook:
  client:
    clientId: ${oauth.facebook.clientId}
    clientSecret: ${oauth.facebook.secret}
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=first_name,last_name,email

vk:
  client:
    clientId: ${oauth.vk.clientId}
    clientSecret: ${oauth.vk.secret}
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
    tokenName: code
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
    grant-type: authorization_code
  resource:
    userInfoUri: https://api.vk.com/method/users.get?fields=bdate,sex,photo_max_orig,friend_status,relation,relation_partner

server:
  session:
    tracking-modes: cookie