spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create