app:
  host: http://localhost:8080
  siteHost: http://localhost:3000

spring:
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: ru.romanov.tonkoslovie.utils.JsonPostgresDialect
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

hikari:
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${database.username}
    password: ${database.password}
    minimumIdle: 1
    maximumPoolSize: 5
    idleTimeout: 10000
    autoCommit: false

redis:
  host: 127.0.0.1
  port: 6379

metrics:
  influxdb:
    active: false
    host: 127.0.0.1
    port: 8086
    database: tonkoslovie
    auth: ${influx.auth}
  console: false

media:
  imageDirectory: /app/tonkoslovie/images
  soundDirectory: /app/tonkoslovie/sounds

security:
  oauth2:
    successRedirectUrl: http://localhost:3000/

google:
  client:
    clientId: ${oauth.google.clientId}
    clientSecret: ${oauth.google.secret}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - openid
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

facebook:
  client:
    clientId: ${oauth.facebook.clientId}
    clientSecret: ${oauth.facebook.secret}
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=first_name,last_name,email

vk:
  client:
    clientId: ${oauth.vk.clientId}
    clientSecret: ${oauth.vk.secret}
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
    grant-type: authorization_code
  resource:
    userInfoUri: https://api.vk.com/method/users.get?fields=bdate,sex,photo_max_orig,friend_status,relation,relation_partner&v=5.73

server:
  servlet:
    session:
      tracking-modes: cookie

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %green(%-5level) %highlight(%logger{36}) - %msg%n"
  level:
    root: info
    com.zaxxer.hikari: info