spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 25
      idle-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/tonkoslovie
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

mail:
  host: http://88.198.165.206:8080
