spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      group-id: "mail-group"
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.romanov.tonkoslovie.*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true

server:
  port: 8084

management:
  server:
    port: 8184
  endpoints:
    web:
      exposure:
        include: health
  influx:
    metrics:
      export:
        enabled: ${INFLUXDB_ENABLED:false}
        db: tonkoslovie
        org: tonkoslovie
        bucket: tonkoslovie
        uri: ${INFLUXDB_URI}
        user-name: ${INFLUXDB_USER}
        password: ${INFLUXDB_PASSWORD}
        token: ${INFLUXDB_ADMIN_TOKEN}
        step: 10s
        api-version: v2
  metrics:
    tags:
      service.name: ${SERVICE_NAME:mail.dev}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%4.-4thread] %clr(%level) %clr([%c{1}]){cyan} %m%n%wEx"
  level:
    root: info
    org.apache.kafka: warn