app:
  host: ${APP_HOST:http://localhost:8080}
  site-host: ${APP_SITE_HOST:http://localhost:3000}

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:5432/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_MIN_POOL_SIZE:3}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:2000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:2000}
      auto-commit: false

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: ru.romanov.tonkoslovie.hibernate.JsonPostgresDialect
        temp:
          use_jdbc_metadata_defaults: false

  liquibase:
    change-log: classpath:db/changelog-master.yaml

  redis:
    host: ${REDIS_HOST:localhost}
    jedis:
      pool:
        max-idle: ${REDIS_MAX_IDLE:3}
        max-active: ${REDIS_MAX_TOTAL:10}

  data:
    redis:
      repositories:
        enabled: false

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost:9092}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/oauth/login/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile
          facebook:
            client-id: ${OAUTH_FB_CLIENT_ID}
            client-secret: ${OAUTH_FB_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/oauth/login/callback/{registrationId}"
            scope:
              - email
              - public_profile
          vk:
            client-id: ${OAUTH_VK_CLIENT_ID}
            client-secret: ${OAUTH_VK_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: post
            redirect-uri: "{baseUrl}/api/oauth/login/callback/{registrationId}"
            scope: email
        provider:
          google:
            token-uri: https://www.googleapis.com/oauth2/v4/token
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            token-uri: https://graph.facebook.com/v7.0/oauth/access_token
            authorization-uri: https://www.facebook.com/v7.0/dialog/oauth
            user-info-uri: https://graph.facebook.com/v7.0/me?fields=first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          vk:
            user-name-attribute: user_id
            token-uri: https://oauth.vk.com/access_token
            authorization-uri: https://oauth.vk.com/authorize
            user-info-uri: https://api.vk.com/method/users.get?fields=id,photo_max_orig&v=5.130

media:
  imageDirectory: ./data/images
  soundDirectory: ./data/sounds

jwt:
  secret: ${JWT_SECRET}

server:
  servlet:
    session:
      tracking-modes: cookie

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8085
  metrics:
    export:
      influx:
        enabled: ${INFLUXDB_ENABLED:false}
        db: tonkoslovie
        uri: ${INFLUXDB_URI}
        user-name: ${INFLUXDB_USER}
        password: ${INFLUXDB_PASSWORD}
        step: 10s

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %green(%-5level) %highlight(%logger{36}) - %msg%n"
  level:
    root: info
    org.eclipse.jetty: warn
    org.apache.kafka: warn
    liquibase: warn