{
 "title": "Tonkoslovie Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "service",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"${bucket}\",\r\n    tag: \"service_name\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_uptime\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r._measurement == \"process_cpu_usage\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    _value:  r.process_cpu_usage * 100.0\r\n  }))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used\")\r\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")"
    }
   ]
  },
  {
   "title": "Open FIles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_files_max\" or r[\"_measurement\"] == \"process_files_open\")\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    value: r._value,\r\n    _measurement: strings.split(v: r._measurement, t: \"_\")[2]\r\n  }))"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_classes_loaded\" or r[\"_measurement\"] == \"jvm_classes_unloaded\")\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    value: r._value,\r\n    _measurement: strings.split(v: r._measurement, t: \"_\")[2]\r\n  }))"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_start_time\")\r\n"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_threads_states\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_cpu_usage\")"
    }
   ]
  },
  {
   "title": "Non-Heap memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used\")\r\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\r\n  |> filter(fn: (r) => r[\"cause\"] == \"G1 Evacuation Pause\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")"
    }
   ]
  },
  {
   "title": "Logback events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logback_events\")"
    }
   ]
  },
  { "title": "Jetty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Jetty threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r._measurement == \"jetty_threads_config_max\" or r._measurement == \"jetty_threads_busy\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    _value: r.jetty_threads_busy / r.jetty_threads_config_max * 100.0\r\n  }))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Jetty threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => contains(value: r._measurement, set: [\"jetty_threads_idle\", \"jetty_threads_busy\", \"jetty_threads_config_max\"]))"
    }
   ]
  },
  {
   "title": "Jetty jobs",
   "type": "timeseries",
   "description": "Number of jobs queued waiting for a thread",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jetty_threads_jobs\")"
    }
   ]
  },
  {
   "title": "Kafka producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total network operations",
     "type": "timeseries",
     "description": "The total number of network operations (reads or writes) on all connections",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_network_io_total\")"
      }
     ]
    },
    {
     "title": "Network IO rate",
     "type": "timeseries",
     "description": "The number of network operations (reads or writes) on all connections per second",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_network_io_rate\")\r\n"
      }
     ]
    },
    {
     "title": "IO wait",
     "type": "timeseries",
     "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_io_wait_time_ns_avg\")"
      }
     ]
    },
    {
     "title": "IO time average",
     "type": "timeseries",
     "description": "The average length of time for I/O per select call in nanoseconds",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_io_time_ns_avg\")"
      }
     ]
    },
    {
     "title": "IO time total",
     "type": "timeseries",
     "description": "The total time the I/O thread spent doing I/O",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_iotime_total\")"
      }
     ]
    },
    {
     "title": "Request rate",
     "type": "timeseries",
     "description": "The number of requests sent per second",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_request_rate\")"
      }
     ]
    },
    {
     "title": "Request total",
     "type": "timeseries",
     "description": "The total number of requests sent",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_request_total\")"
      }
     ]
    },
    {
     "title": "Incoming byte total",
     "type": "timeseries",
     "description": "The total number of bytes read off all sockets",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_incoming_byte_total\")"
      }
     ]
    },
    {
     "title": "Incoming byte rate",
     "type": "timeseries",
     "description": "The number of bytes read off all sockets per second",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_incoming_byte_rate\")"
      }
     ]
    },
    {
     "title": "Response rate",
     "type": "timeseries",
     "description": "The number of responses received per second",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_response_rate\")"
      }
     ]
    },
    {
     "title": "Response total",
     "type": "timeseries",
     "description": "The total number of responses received",
     "gridPos": { "h": 8, "w": 3, "x": 15, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_response_total\")"
      }
     ]
    },
    {
     "title": "Outgoind byte total",
     "type": "timeseries",
     "description": "The total number of outgoing bytes sent to all servers",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_outgoing_byte_total\")"
      }
     ]
    },
    {
     "title": "Outgoing byte rate",
     "type": "timeseries",
     "description": "The number of outgoing bytes sent to all servers per second",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_outgoing_byte_rate\")"
      }
     ]
    },
    {
     "title": "Select total",
     "type": "timeseries",
     "description": "The total number of times the I/O layer checked for new I/O to perform",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_select_total\")"
      }
     ]
    },
    {
     "title": "Select rate",
     "type": "timeseries",
     "description": "The number of times the I/O layer checked for new I/O to perform per second",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_select_rate\")"
      }
     ]
    },
    {
     "title": "Max batch size",
     "type": "timeseries",
     "description": "The max number of bytes sent per partition per-request",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_batch_size_max\")"
      }
     ]
    },
    {
     "title": "Batch split",
     "type": "timeseries",
     "description": "The total number of batch splits",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_batch_split_total\")"
      }
     ]
    },
    {
     "title": "Throttle time",
     "type": "timeseries",
     "description": "The average time in ms a request was throttled by a broker",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_produce_throttle_time_avg\")"
      }
     ]
    },
    {
     "title": "Waiting threads",
     "type": "timeseries",
     "description": "The number of user threads blocked waiting for buffer memory to enqueue their records",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"service_name\"] == \"${service}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kafka_producer_waiting_threads\")"
      }
     ]
    }
   ]
  }
 ]
}