spring:
  elasticsearch:
    uris: ${ELASTIC_URL:http://localhost:9200}

server:
  port: 8083

management:
  server:
    port: 8183
  endpoints:
    web:
      exposure:
        include: health
  influx:
    metrics:
      export:
        enabled: ${INFLUXDB_ENABLED:false}
        db: tonkoslovie
        org: tonkoslovie
        bucket: tonkoslovie
        uri: ${INFLUXDB_URI}
        user-name: ${INFLUXDB_USER}
        password: ${INFLUXDB_PASSWORD}
        token: ${INFLUXDB_ADMIN_TOKEN}
        step: 10s
        api-version: v2
  metrics:
    tags:
      service.name: ${SERVICE_NAME:audit.dev}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%4.-4thread] %clr(%level) %clr([%c{1}]){cyan} %m%n%wEx"
  level:
    root: info